version: '3.4'

services:

  api:
    container_name: msTourism2
    build: ./api
    volumes:
      - ./api/msTourism2:/var/msTourism2
    ports:
      - :3000:3000
    depends_on:
      - mongodb

  mongodb:
    container_name: mongoStack
    image: mongo:3.4
    volumes:
      - ./mongodb/db:/data/db
    ports:
      - 127.0.0.1:27017:27017


